name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "🐛 "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔬 Reproduction Steps
      description: Steps to reproduce the behavior
      placeholder: |
        1. Import '...'
        2. Use type '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 🎯 Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: 🔍 Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: e.g., macOS, Windows, Linux
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      placeholder: e.g., 18.17.0
    validations:
      required: true

  - type: input
    id: typescript-version
    attributes:
      label: TypeScript Version
      placeholder: e.g., 5.2.0
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Package Version
      placeholder: e.g., 0.6.1
    validations:
      required: true

  - type: textarea
    id: minimal-reproduction
    attributes:
      label: 📋 Minimal Reproduction
      description: Please provide a minimal code example that reproduces the issue
      render: typescript
      placeholder: |
        // TypeScript code that reproduces the issue
        import { ... } from '@thewlabs/ts-reset'
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 🤔 Additional Context
      description: Add any other context about the problem here.

  - type: textarea
    id: possible-solution
    attributes:
      label: ✅ Possible Solution
      description: If you have ideas on how to fix this, please share them here.
