name: 🚀 Feature Request
description: Suggest a new feature or enhancement
title: "🚀 "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: feature-description
    attributes:
      label: 🚀 Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: What feature would you like to see added?
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: 🤔 Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: Describe the problem this feature would solve...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 💡 Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: example-usage
    attributes:
      label: 📝 Example Usage
      description: Show how this feature would be used
      render: typescript
      placeholder: |
        // Example of how the feature would be used
        import { newFeature } from '@thewlabs/ts-reset'
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: What alternatives have you considered?
      placeholder: Describe any alternative solutions you've considered...

  - type: checkboxes
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would this be a breaking change?
      options:
        - label: This would be a breaking change
        - label: This would be backwards compatible

  - type: textarea
    id: additional-context
    attributes:
      label: 🤔 Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
